# Generated by Django 4.0.5 on 2022-07-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='balance',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
